-- vim.api.nvim_create_autocmd({ "CmdlineEnter" }, {
-- 	callback = function()
-- 		vim.opt.laststatus = 0
-- 	end,
--
--
-- vim.api.nvim_create_autocmd({ "CmdlineLeave" }, {
-- 	callback = function()
-- 		vim.opt.laststatus = 3
-- 	end,
-- })
